menu:
    Site: /
    #微博: http://weibo.com/
    rss: /atom.xml
    github: https://github.com/NJUST-FishTeam/

favicon: /ICPC-Logo-Fishead.png
logo: /ICPC-Logo-Fishead.png

# comment
# e.g disqus: seansun
disqus:
duoshuo:

# google-analytics:
#ga: UA-65933410-1
# baidu-analytics:
#ba: //hm.baidu.com/hm.js?a36e15d9e2adec9a21fcdd9f686b1ed2

# 备案号
beian: 浙ICP备15012901号-2
